---
title: "Cell-cell interaction analysis: Zhang et al."
author: "Yingxin Lin"
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    number_sections: yes
    toc: yes
    fig_height: 8
    fig_width: 8
    toc_float:
      collapsed: true
      smooth_scroll: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE,warning = FALSE)
```


# Data and package

```{r}
library(scran)
library(SingleCellExperiment)
library(scater)
library(scattermore)
library(moon)
library(ggplot2)
library(ggthemes)
library(ggpubr)
library(reshape2)
library(dplyr)
library(stringr)
library(pheatmap)
library(CellChat)
library(gridExtra)
library(RColorBrewer)
```


```{r}
meta_zhang <- readRDS("results/zhang_results/meta_zhang.rds")
coldata_zhang <- readRDS("results/zhang_results/coldata_zhang.rds")
```


```{r}
severity_color <- c("#2ca02c", "#FFD92F", "#7570B3", "#1f77b4")
names(severity_color) <- c("Healthy", "Moderate", "Severe", "Conv")
```




```{r}
# CCI results (Cellchat)
cellchat_res_list <- readRDS("results/zhang_results/zhang_cellchat_res_list.rds")
```



```{r}

rankNet_byCellType <- function(object, slot.name = "netP", 
                               x.rotation = 90, title = NULL, color.use = NULL, 
                               bar.w = 0.75, font.size = 8) 
{
    object1 <- methods::slot(object, slot.name)
    prob1 = object1$prob
    df <- melt(apply(prob1, 3, function(x) {
        df <- melt(x)
        colnames(df) <- c("Ligand", "Receptor", "value")
        df
    }))
    df <- df[, c("Ligand", "Receptor", "L1", "value")]
    colnames(df)[3] <- "Pathway"
    return(df)
    
    
}
```

# Overall pattern analysis

```{r}

rankNet_byCellType_list <- lapply(cellchat_res_list, rankNet_byCellType)

rankNet_byCellType_list <- melt(rankNet_byCellType_list)
rankNet_byCellType_list$Ligand_group <- unlist(lapply(strsplit(as.character(rankNet_byCellType_list$Ligand), 
                                                               "_"), "[[", 1))
rankNet_byCellType_list$Receptor_group <- unlist(lapply(strsplit(as.character(rankNet_byCellType_list$Receptor), 
                                                                 "_"), "[[", 1))


saveRDS(rankNet_byCellType_list, file = "results/zhang_results/rankNet_byCellType_list_zhang.rds")

```



```{r}

rankNet_byGroup_agg <- aggregate(rankNet_byCellType_list$value, 
                                 list(rankNet_byCellType_list$Ligand_group,
                                      rankNet_byCellType_list$Receptor_group,
                                      rankNet_byCellType_list$L1,
                                      rankNet_byCellType_list$Pathway),
                                 sum)


colnames(rankNet_byGroup_agg) <- c("Ligand_group", 
                                   "Receptor_group",
                                   "sample",
                                   "Pathway",
                                   "value")
features <- paste(rankNet_byGroup_agg$Ligand_group,
                  rankNet_byGroup_agg$Receptor_group,
                  rankNet_byGroup_agg$Pathway, sep = "_")

rankNet_byGroup_agg$features <- features
```


```{r}

rankNet_byGroup_agg_all <- dcast2(rankNet_byGroup_agg, 
                                  features ~ sample, 
                                  fun.aggregate = sum, value.var = "value")
rankNet_byGroup_agg_all <- rankNet_byGroup_agg_all[rowSums(rankNet_byGroup_agg_all) > 0, ]
rankNet_byGroup_agg_all <- rankNet_byGroup_agg_all[rowSums(rankNet_byGroup_agg_all!=0) > 2, ]

```



## Feature selction: kruskal test

```{r}

kruskal_pvalue <- list()
for (i in 1:nrow(rankNet_byGroup_agg_all)) {
    if (i %% 100 == 0) print(i)
    
    kruskal_res <- try(kruskal.test(unlist(rankNet_byGroup_agg_all[i,]) ~ meta_zhang[colnames(rankNet_byGroup_agg_all), ]$Condition), silent = TRUE)
    kruskal_pvalue[[i]] <- try(kruskal_res$p.value, silent = TRUE)
    
}

kruskal_pvalue <- lapply(kruskal_pvalue, function(x) {
    if (class(x) == "try-error") {
        x <- NULL
    }
    x
})
names(kruskal_pvalue) <- rownames(rankNet_byGroup_agg_all)
kruskal_pvalue <- unlist(kruskal_pvalue)

kruskal_pvalue <- p.adjust(kruskal_pvalue, method = "BH")
sort(kruskal_pvalue)[1:20]
saveRDS(kruskal_pvalue, file = "results/Zhang_results/CCI_kruskal_pvalue_condition_zhang.rds")
```



## PCA 

```{r}

pca_patient <- prcomp(t(-1/log(rankNet_byGroup_agg_all[names(kruskal_pvalue[kruskal_pvalue < 0.2]),])), scale. = TRUE, center = TRUE)
library(ggrepel)
pca1 <- ggplot(data.frame(pca_patient$x), aes(x = pca_patient$x[, 1],
                                              y = pca_patient$x[, 2],
                                              color = meta_zhang[rownames(pca_patient$x),]$Condition)) +
    geom_point(size = 4, alpha = 0.8) +
    # geom_text_repel(aes(label = rownames(pca_patient$x))) +
    theme_yx() +
    theme(aspect.ratio = 1) +
    scale_color_manual(values = severity_color) +
    xlab("PCA1") +
    ylab("PCA2") +
    labs(color = "")

pca2 <- ggplot(data.frame(pca_patient$x), aes(x = pca_patient$x[, 1],
                                              y = pca_patient$x[, 3],
                                              color = meta_zhang[rownames(pca_patient$x),]$Condition)) +
    geom_point(size = 3, alpha = 0.8) +
    # geom_text_repel(aes(label = rownames(pca_patient$x))) +
    theme_yx() +
    theme(aspect.ratio = 1) +
    scale_color_manual(values = severity_color) +
    xlab("PCA1") +
    ylab("PCA3") +
    labs(color = "")

pca3 <- ggplot(data.frame(pca_patient$x), aes(x = pca_patient$x[, 2],
                                              y = pca_patient$x[, 3],
                                              color = meta_zhang[rownames(pca_patient$x),]$Condition)) +
    geom_point(size = 3, alpha = 0.8) +
    # geom_text_repel(aes(label = rownames(pca_patient$x))) +
    theme_yx() +
    theme(aspect.ratio = 1) +
    scale_color_manual(values = severity_color) +
    xlab("PCA2") +
    ylab("PCA3") +
    labs(color = "")

ggarrange(pca1, pca2, pca3, align = "hv", 
          common.legend = TRUE, ncol = 2, nrow = 2)

```




## Aggregation by samples

```{r}
aff_mat_bySample <- lapply(split(rankNet_byGroup_agg, rankNet_byGroup_agg$sample),
                           function(x) dcast2(x, Ligand_group~Receptor_group,
                                              fun.aggregate = mean, value.var = "value"))
all_cellTypes <- sort(unique(unlist(lapply(aff_mat_bySample, dimnames))))

aff_mat_bySample <- lapply(aff_mat_bySample, function(x) {
    mat <- matrix(0, ncol = length(all_cellTypes), nrow = length(all_cellTypes))
    colnames(mat) <- rownames(mat) <- all_cellTypes
    mat[rownames(x), colnames(x)] <- as.matrix(x)
    mat
})


selected_cellTypes <- all_cellTypes[!all_cellTypes %in% c("intermediate", "unassigned",
                                                         "RBC")]
aff_mat_bySample <- lapply(aff_mat_bySample, function(x) {
  x <- x[selected_cellTypes, selected_cellTypes]
  x
})

aff_mat_bySample <- lapply(aff_mat_bySample, function(x) {
    (x - min(x))/(max(x) - min(x))
})

p <- lapply(1:length(aff_mat_bySample), function(i) {
    pheatmap(aff_mat_bySample[[i]],
             cluster_cols = FALSE, 
             cluster_rows = FALSE,
             main = names(aff_mat_bySample)[i],
             color =  colorRampPalette(c("white", 
                                         brewer.pal(n = 7, 
                                                    name = "Reds")))(100))
})

pdf("figures/zhangEtAl/cellchat_CCI_network_sample_byCellType.pdf", 
    width = 20, height = 20)
do.call(grid.arrange, list(grobs = lapply(p, function(x) x$gtable), ncol = 5))
dev.off()
# 
```


```{r}

severe_patients <- rownames(meta_zhang)[meta_zhang$Condition == "Severe"]
aff_mat_severe <- Reduce("+", aff_mat_bySample[names(aff_mat_bySample) %in% severe_patients])/length(severe_patients)
aff_mat_severe <- aff_mat_severe[selected_cellTypes, selected_cellTypes]

moderate_patients <- rownames(meta_zhang)[meta_zhang$Condition == "Moderate"]
aff_mat_moderate <- Reduce("+", aff_mat_bySample[names(aff_mat_bySample) %in% moderate_patients])/length(moderate_patients)
aff_mat_moderate <- aff_mat_moderate[selected_cellTypes, selected_cellTypes]


control_patients <- rownames(meta_zhang)[meta_zhang$Condition == "Healthy"]
aff_mat_control <- Reduce("+", aff_mat_bySample[names(aff_mat_bySample) %in% control_patients])/length(control_patients)
aff_mat_control <- aff_mat_control[selected_cellTypes, selected_cellTypes]

Conv_patients <- rownames(meta_zhang)[meta_zhang$Condition == "Conv"]
aff_mat_Conv <- Reduce("+", aff_mat_bySample[names(aff_mat_bySample) %in% Conv_patients])/length(Conv_patients)
aff_mat_Conv <- aff_mat_Conv[selected_cellTypes, selected_cellTypes]

p_severe <- pheatmap(aff_mat_severe, cluster_cols = FALSE, 
                     cluster_rows = FALSE,
                     main = "severe (average across samples)",
                     color =  colorRampPalette(c("white", 
                                                 brewer.pal(n = 7, 
                                                            name = "Reds")))(100),
                     breaks = seq(0, max(aff_mat_severe), max(aff_mat_severe)/100))
library(RColorBrewer)
p_moderate <- pheatmap(aff_mat_moderate, 
                       cluster_cols = FALSE, 
                       cluster_rows = FALSE,
                       main = "moderate (average across samples)",
                       color =  colorRampPalette(c("white", 
                                                   brewer.pal(n = 7, 
                                                              name = "Reds")))(100),
                       breaks = seq(0, max(aff_mat_moderate), max(aff_mat_moderate)/100))


p_control <- pheatmap(aff_mat_control, 
                      cluster_cols = FALSE, 
                      cluster_rows = FALSE,
                      main = "control (average across samples)",
                      color =  colorRampPalette(c("white", 
                                                  brewer.pal(n = 7, 
                                                             name = "Reds")))(100),
                      breaks = seq(0, max(aff_mat_control), max(aff_mat_control)/100))


p_Conv <- pheatmap(aff_mat_Conv, 
                      cluster_cols = FALSE, 
                      cluster_rows = FALSE,
                      main = "convalescence (average across samples)",
                      color =  colorRampPalette(c("white", 
                                                  brewer.pal(n = 7, 
                                                             name = "Reds")))(100),
                      breaks = seq(0, max(aff_mat_Conv), max(aff_mat_Conv)/100))


pdf("figures/zhangEtAl/cellchat_CCI_network_byCondition_noScale.pdf", 
    width = 8, height = 8)
do.call(grid.arrange, list(grobs = list(p_control$gtable,
                                        p_moderate$gtable,
                                        p_severe$gtable,
                                        p_Conv$gtable), ncol = 2))
dev.off()
```


```{r}
aff_mat_diff <- aff_mat_severe - aff_mat_moderate

keep <- intersect(names(which(colSums(aff_mat_diff) != 0)),
                  names(which(rowSums(aff_mat_diff) != 0)))

pheatmap(aff_mat_diff,
         cluster_cols = FALSE, 
         cluster_rows = FALSE,
         color =  colorRampPalette(c("blue", "white", "red"))(100),
         breaks = c(seq(min(aff_mat_diff), 0, (0 - min(aff_mat_diff))/50),
                    seq(0.01, max(aff_mat_diff), (max(aff_mat_diff))/50)),
         main = "server - moderate (zhang et al.)",
         #file = "figures/zhangEtAl/cellchat_CCI_network_byCondition_diff_severe.pdf",
         width = 8,
         height = 7)

aff_mat_diff <- aff_mat_Conv - aff_mat_moderate

keep <- intersect(names(which(colSums(aff_mat_diff) != 0)),
                  names(which(rowSums(aff_mat_diff) != 0)))

pheatmap(aff_mat_diff,
         cluster_cols = FALSE, 
         cluster_rows = FALSE,
         color =  colorRampPalette(c("blue", "white", "red"))(100),
         breaks = c(seq(min(aff_mat_diff), 0, (0 - min(aff_mat_diff))/50),
                    seq(0.01, max(aff_mat_diff), (max(aff_mat_diff))/50)),
         main = "convalescence - moderate (zhang et al.)",
         #file = "figures/zhangEtAl/cellchat_CCI_network_byCondition_diff_conv.pdf",
         width = 8,
         height = 7)


aff_mat_diff <- aff_mat_severe - aff_mat_control

keep <- intersect(names(which(colSums(aff_mat_diff) != 0)),
                  names(which(rowSums(aff_mat_diff) != 0)))

pheatmap(aff_mat_diff,
         cluster_cols = FALSE, 
         cluster_rows = FALSE,
         color =  colorRampPalette(c("blue", "white", "red"))(100),
         breaks = c(seq(min(aff_mat_diff), 0, (0 - min(aff_mat_diff))/50),
                    seq(0.01, max(aff_mat_diff), (max(aff_mat_diff))/50)),
         main = "server - control (zhang et al.)",
         #file = "figures/zhangEtAl/cellchat_CCI_network_byCondition_diff_severe_vs_control.pdf",
         width = 8,
         height = 7)

aff_mat_diff <- aff_mat_moderate - aff_mat_control


pheatmap(aff_mat_diff,
         cluster_cols = FALSE, 
         cluster_rows = FALSE,
         color =  colorRampPalette(c("blue", "white", "red"))(100),
         breaks = c(seq(min(aff_mat_diff), 0, (0 - min(aff_mat_diff))/50),
                    seq(0.01, max(aff_mat_diff), (max(aff_mat_diff))/50)),
         main = "moderate - control (zhang et al.)",
         #file = "figures/zhangEtAl/cellchat_CCI_network_byCondition_diff_moderate_vs_control.pdf",
         width = 8,
         height = 7)
```

```{r}
cellType_col <- readRDS("results/pbmc_cellType_col.rds")
```

```{r}
mat <- aff_mat_control
#mat <- as.matrix(mat)

#mat <- t(Matrix::tril(mat)) + Matrix::triu(mat)
#mat <- mat + t(mat)

cci_control <- melt(as.matrix(mat))
colnames(cci_control) <- c("Ligand", "Receptor", "n")
library(igraph)
library(ggraph)
g <- graph_from_data_frame(data.frame(cci_control))
E(g)$weights <- ifelse(cci_control$n == 0,
                       1e-10, abs(cci_control$n))
#E(g)$sign <- ifelse(sign(cci_control$n) == 1, "#d62728", "#1f77b4")


V(g)$color <- cellType_col[V(g)$name]
# pdf("figures/ZhangEtAl/cellchat_CCI_network_byCondition_Control_network.pdf",
#     width = 8,
#     height = 6)
plot(g, 
     vertex.size = 20,
     vertex.color = V(g)$color,
     vertex.label.color = "black",
     vertex.label.cex = 1,
     edge.width = E(g)$weights * 20,
     edge.arrow.size = log(1/E(g)$weights)/50,
     #edge.arrow.size = 0.01,
     #edge.color = E(g)$sign,
     edge.curved = 0.3,
     layout = layout_in_circle,
     main = "Control")
# dev.off()
```

```{r}
mat <- aff_mat_moderate
#mat <- as.matrix(mat)

#mat <- t(Matrix::tril(mat)) + Matrix::triu(mat)
#mat <- mat + t(mat)

cci_moderate <- melt(as.matrix(mat))
colnames(cci_moderate) <- c("Ligand", "Receptor", "n")
library(igraph)
library(ggraph)
g <- graph_from_data_frame(data.frame(cci_moderate))
E(g)$weights <- ifelse(cci_moderate$n == 0,
                       1e-10, abs(cci_moderate$n))
#E(g)$sign <- ifelse(sign(cci_moderate$n) == 1, "#d62728", "#1f77b4")
g <- delete_edges(g, E(g)[cci_moderate$n == 0])

V(g)$color <- cellType_col[V(g)$name]
# pdf("figures/ZhangEtAl/cellchat_CCI_network_byCondition_moderate_network.pdf",
#     width = 8,
#     height = 6)
plot(g, 
     vertex.size = 20,
     vertex.color = V(g)$color,
     vertex.label.color = "black",
     vertex.label.cex = 1,
     edge.width = E(g)$weights * 20,
     edge.arrow.size = log(1/E(g)$weights)/50,
     #edge.arrow.size = 0.01,
     #edge.color = E(g)$sign,
     edge.curved = 0.3,
     layout = layout_in_circle,
     main = "moderate")
# dev.off()
```



```{r}
mat <- aff_mat_severe

cci_severe <- melt(as.matrix(mat))
colnames(cci_severe) <- c("Ligand", "Receptor", "n")
library(igraph)
library(ggraph)
g <- graph_from_data_frame(data.frame(cci_severe))

E(g)$weights <- ifelse(cci_severe$n == 0,
                       1e-10, abs(cci_severe$n))

g <- delete_edges(g, E(g)[cci_severe$n == 0])
V(g)$color <- cellType_col[V(g)$name]
# pdf("figures/ZhangEtAl/cellchat_CCI_network_byCondition_severe_network.pdf",
#     width = 8,
#     height = 6)
plot(g, 
     vertex.size = 20,
     vertex.color = V(g)$color,
     vertex.label.color = "black",
     vertex.label.cex = 1,
     edge.width = E(g)$weights * 20,
     edge.arrow.size = log(1/E(g)$weights)/50,
     #edge.arrow.size = 0.01,
     #edge.color = E(g)$sign,
     edge.curved = 0.3,
     layout = layout_in_circle,
     main = "severe")
# dev.off()
```




# Session Info

```{r}
sessionInfo()
```



